language: python
python: 3.6
env:
  - TOXENV=py36
  - TOXENV=kinto-master
  - TOXENV=flake8
install: pip install -U tox
script: tox
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - TOX_ENV=py37
